### ISSUE TITLE
Add support for PyOpenGL (GLES2)

### ISSUE THREAD

**Issue by Elsarques** [tareksander/termux-gui-python-bindings#12]
I'm trying to use PyOpenGL, but it just throws an error, and I don't know if it's related to the bindings or even the Termux:GUI, but i'm new in this thing of shaders, and I want to know how to use PyOpenGL with Termux:GUI

here's the error:
`Traceback (most recent call last):
  File "/data/data/com.termux/files/home/3DEngine/main.py", line 2, in <module>
    from OpenGL.GLES2 import *
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/OpenGL/GLES2/__init__.py", line 2, in <module>
    from OpenGL.raw.GLES2._types import *
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/OpenGL/raw/GLES2/_types.py", line 5, in <module>
    _error_checker = _ErrorChecker( _p, _p.GLES2.glGetError )
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/OpenGL/error.py", line 183, in __init__
    self._isValid = platform.CurrentContextIsValid
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/OpenGL/platform/baseplatform.py", line 15, in __get__
    value = self.fget( obj )
            ^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/OpenGL/platform/baseplatform.py", line 356, in CurrentContextIsValid
    return self.GetCurrentContext
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/OpenGL/platform/baseplatform.py", line 15, in __get__
    value = self.fget( obj )
            ^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/OpenGL/platform/glx.py", line 100, in GetCurrentContext
    return self.GLX.glXGetCurrentContext
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'glXGetCurrentContext'`

And here's the code:

`import OpenGL
  from OpenGL.GLES2 import *
  import termuxgui as tg
  import time

  with tg.Connection() as c:
     # create a new Activity. By default, a  new Task as created.
     a = tg.Activity(c)
    # you can find the Task under a.t

    # create the TextView.
    tv = tg.TextView(a, "Hello world!")

    time.sleep(5)
    tv.settext("Goodbye world!")

    time.sleep(5)`

**Comment by Elsarques** [comment]
Solved by installing python-opengl from the TUR repo
